# Generated by Django 3.0 on 2020-07-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exceldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('bevarage_type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('total_volume', models.IntegerField()),
                ('total_value', models.FloatField()),
                ('unit_price', models.FloatField()),
            ],
        ),
    ]
